// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/device_info.dart';
import 'api/disk_scan.dart';
import 'api/gui_log.dart';
import 'api/pcas.dart';
import 'api/simple.dart';
import 'api/sysinfo.dart';
import 'api/utils.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AdapterInfo dco_decode_adapter_info(dynamic raw);

  @protected
  AppIconPixels dco_decode_app_icon_pixels(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DiskInfo dco_decode_box_autoadd_disk_info(dynamic raw);

  @protected
  DiskInfo dco_decode_disk_info(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  InstalledAppInfo dco_decode_installed_app_info(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AdapterInfo> dco_decode_list_adapter_info(dynamic raw);

  @protected
  List<bool> dco_decode_list_bool(dynamic raw);

  @protected
  List<DiskInfo> dco_decode_list_disk_info(dynamic raw);

  @protected
  List<InstalledAppInfo> dco_decode_list_installed_app_info(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProcessEntry> dco_decode_list_process_entry(dynamic raw);

  @protected
  List<StartupItemInfo> dco_decode_list_startup_item_info(dynamic raw);

  @protected
  MemoryInfo dco_decode_memory_info(dynamic raw);

  @protected
  MonitorSize dco_decode_monitor_size(dynamic raw);

  @protected
  MonitorWorkSize dco_decode_monitor_work_size(dynamic raw);

  @protected
  NetInfo dco_decode_net_info(dynamic raw);

  @protected
  NetQuality dco_decode_net_quality(dynamic raw);

  @protected
  DiskInfo? dco_decode_opt_box_autoadd_disk_info(dynamic raw);

  @protected
  ProcessEntry dco_decode_process_entry(dynamic raw);

  @protected
  StartupItemInfo dco_decode_startup_item_info(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AdapterInfo sse_decode_adapter_info(SseDeserializer deserializer);

  @protected
  AppIconPixels sse_decode_app_icon_pixels(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DiskInfo sse_decode_box_autoadd_disk_info(SseDeserializer deserializer);

  @protected
  DiskInfo sse_decode_disk_info(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  InstalledAppInfo sse_decode_installed_app_info(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AdapterInfo> sse_decode_list_adapter_info(SseDeserializer deserializer);

  @protected
  List<bool> sse_decode_list_bool(SseDeserializer deserializer);

  @protected
  List<DiskInfo> sse_decode_list_disk_info(SseDeserializer deserializer);

  @protected
  List<InstalledAppInfo> sse_decode_list_installed_app_info(
      SseDeserializer deserializer);

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProcessEntry> sse_decode_list_process_entry(
      SseDeserializer deserializer);

  @protected
  List<StartupItemInfo> sse_decode_list_startup_item_info(
      SseDeserializer deserializer);

  @protected
  MemoryInfo sse_decode_memory_info(SseDeserializer deserializer);

  @protected
  MonitorSize sse_decode_monitor_size(SseDeserializer deserializer);

  @protected
  MonitorWorkSize sse_decode_monitor_work_size(SseDeserializer deserializer);

  @protected
  NetInfo sse_decode_net_info(SseDeserializer deserializer);

  @protected
  NetQuality sse_decode_net_quality(SseDeserializer deserializer);

  @protected
  DiskInfo? sse_decode_opt_box_autoadd_disk_info(SseDeserializer deserializer);

  @protected
  ProcessEntry sse_decode_process_entry(SseDeserializer deserializer);

  @protected
  StartupItemInfo sse_decode_startup_item_info(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_adapter_info(AdapterInfo self, SseSerializer serializer);

  @protected
  void sse_encode_app_icon_pixels(AppIconPixels self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_disk_info(
      DiskInfo self, SseSerializer serializer);

  @protected
  void sse_encode_disk_info(DiskInfo self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_installed_app_info(
      InstalledAppInfo self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_adapter_info(
      List<AdapterInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bool(List<bool> self, SseSerializer serializer);

  @protected
  void sse_encode_list_disk_info(List<DiskInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_installed_app_info(
      List<InstalledAppInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_64_strict(
      Uint64List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_process_entry(
      List<ProcessEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_startup_item_info(
      List<StartupItemInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_memory_info(MemoryInfo self, SseSerializer serializer);

  @protected
  void sse_encode_monitor_size(MonitorSize self, SseSerializer serializer);

  @protected
  void sse_encode_monitor_work_size(
      MonitorWorkSize self, SseSerializer serializer);

  @protected
  void sse_encode_net_info(NetInfo self, SseSerializer serializer);

  @protected
  void sse_encode_net_quality(NetQuality self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_disk_info(
      DiskInfo? self, SseSerializer serializer);

  @protected
  void sse_encode_process_entry(ProcessEntry self, SseSerializer serializer);

  @protected
  void sse_encode_startup_item_info(
      StartupItemInfo self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
