// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// 获取主显示器名。
/// TODO(占位)：真实多显示器枚举（EnumDisplayMonitors 等）的命名规则规格整理未确认，
/// 主显示器按约定固定命名为 "Display 0"。
Future<List<String>> getMainMonitor() =>
    RustLib.instance.api.crateApiDeviceInfoGetMainMonitor();

/// 获取主显示器分辨率：SM_CXSCREEN=0 / SM_CYSCREEN=1。
Future<MonitorSize> getMonitorSize() =>
    RustLib.instance.api.crateApiDeviceInfoGetMonitorSize();

/// 获取虚拟桌面工作区：SM_XVIRTUALSCREEN=76 / SM_YVIRTUALSCREEN=77 /
/// SM_CXVIRTUALSCREEN=78 / SM_CYVIRTUALSCREEN=79。
Future<MonitorWorkSize> getMonitorWorkSize() =>
    RustLib.instance.api.crateApiDeviceInfoGetMonitorWorkSize();

/// 主显示器分辨率（像素）
class MonitorSize {
  final int width;
  final int height;

  const MonitorSize({
    required this.width,
    required this.height,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MonitorSize &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height;
}

/// 虚拟桌面（全部显示器的边界矩形）工作区信息（像素）
class MonitorWorkSize {
  final int x;
  final int y;
  final int width;
  final int height;

  const MonitorWorkSize({
    required this.x,
    required this.y,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      x.hashCode ^ y.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MonitorWorkSize &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          width == other.width &&
          height == other.height;
}
