// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dir_size_limited`, `format_size`, `hash_file_sha256`, `is_skipped_top_dir`, `locate_rule_file`, `system_root_dir`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DirStat`, `DupGroup`, `EntryResult`, `ScanResult`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

Future<String> scanDeepClean() =>
    RustLib.instance.api.crateApiDiskScanScanDeepClean();

/// 清理深度清理扫描结果（本工程新增的配套 API，不在原始 95 个 codec 面内）。
/// `result_json`：`scan_deep_clean` 返回的 JSON 字符串。
Future<void> cleanDeepClean({required String resultJson}) =>
    RustLib.instance.api.crateApiDiskScanCleanDeepClean(resultJson: resultJson);

Future<void> cancelDeepCleanScan() =>
    RustLib.instance.api.crateApiDiskScanCancelDeepCleanScan();

Future<List<String>> getRecycleBinSize() =>
    RustLib.instance.api.crateApiDiskScanGetRecycleBinSize();

Future<void> emptyRecycleBin() =>
    RustLib.instance.api.crateApiDiskScanEmptyRecycleBin();

Future<void> openRecycleBinFolder() =>
    RustLib.instance.api.crateApiDiskScanOpenRecycleBinFolder();

Future<List<bool>> checkFilesExists({required List<String> paths}) =>
    RustLib.instance.api.crateApiDiskScanCheckFilesExists(paths: paths);

Future<void> deleteFile({required List<String> paths}) =>
    RustLib.instance.api.crateApiDiskScanDeleteFile(paths: paths);

Future<void> deleteSingleFile({required String path}) =>
    RustLib.instance.api.crateApiDiskScanDeleteSingleFile(path: path);

Future<void> openFileDir({required String path}) =>
    RustLib.instance.api.crateApiDiskScanOpenFileDir(path: path);

Future<String> largeFileScan(
        {required String root, required BigInt minSizeMb}) =>
    RustLib.instance.api
        .crateApiDiskScanLargeFileScan(root: root, minSizeMb: minSizeMb);

Future<void> cancelLargeFileScan() =>
    RustLib.instance.api.crateApiDiskScanCancelLargeFileScan();

Future<String> duplicateFileScan({required String root}) =>
    RustLib.instance.api.crateApiDiskScanDuplicateFileScan(root: root);

Future<void> cancelDuplicateFileScan() =>
    RustLib.instance.api.crateApiDiskScanCancelDuplicateFileScan();

Future<String> systemDiskScan() =>
    RustLib.instance.api.crateApiDiskScanSystemDiskScan();

Future<void> cancelSystemDiskScan() =>
    RustLib.instance.api.crateApiDiskScanCancelSystemDiskScan();

Future<void> clearSystemDiskScanData() =>
    RustLib.instance.api.crateApiDiskScanClearSystemDiskScanData();
