// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `append_log`, `open_log_file`, `write_line`

/// 追加一条 INFO 级 GUI 日志，返回已写入的行文本。
Future<String> info({required String msg}) =>
    RustLib.instance.api.crateApiGuiLogInfo(msg: msg);

/// 追加一条 WARN 级 GUI 日志，返回已写入的行文本。
Future<String> warn({required String msg}) =>
    RustLib.instance.api.crateApiGuiLogWarn(msg: msg);

/// 追加一条 ERROR 级 GUI 日志，返回已写入的行文本。
Future<String> error({required String msg}) =>
    RustLib.instance.api.crateApiGuiLogError(msg: msg);
