// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 拉起 PCAS 认证客户端：
/// - 客户端已安装（路径存在）→ 直接 spawn 该 exe；
/// - 未安装 → 经 explorer.exe 打开默认浏览器访问兜底链接（占位行为）。
Future<void> openPcasClient() =>
    RustLib.instance.api.crateApiPcasOpenPcasClient();
