// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 应用初始化：确保日志目录（exe 目录 logs\，失败回退当前工作目录 logs\）
/// 存在，并记录初始化完成标记。返回 `Ok(())`。
Future<void> initApp() => RustLib.instance.api.crateApiSimpleInitApp();
