// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `align4`, `apply_and_mask`, `bitmap_size`, `collect_uninstall`, `collect_version_strings`, `display_icon_index`, `display_icon_path`, `expand_env_vars`, `extract_pe_icon`, `hosts_path`, `icon_to_rgba`, `is_default_host_line`, `load_version_map`, `mount_letter`, `read_run_key`, `read_version_block`, `run_tool`, `shell_icon`, `to_wide`, `with_com_initialized`, `wmi_connection`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Win32_ComputerSystem`, `Win32_NetworkAdapterConfiguration`, `Win32_OperatingSystem`, `Win32_QuickFixEngineering`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 禁用系统代理（写 HKCU\...\Internet Settings\ProxyEnable = 0）
Future<void> disableProxy() =>
    RustLib.instance.api.crateApiSysinfoDisableProxy();

/// 启用指定网络适配器（参考实现走 SetupDi 系列 API；这里退化为 netsh，需管理员权限）
Future<void> enableAdapter({required String adapterName}) =>
    RustLib.instance.api.crateApiSysinfoEnableAdapter(adapterName: adapterName);

/// 修复 hosts：把 hosts 恢复为默认内容（仅保留空行/注释/localhost 行）。
/// 返回是否实际执行了修复。修改 hosts 需要管理员权限。
Future<bool> fixHostConfiged() =>
    RustLib.instance.api.crateApiSysinfoFixHostConfiged();

/// 适配器数量（条数）
Future<BigInt> getAdapterSize() =>
    RustLib.instance.api.crateApiSysinfoGetAdapterSize();

/// 网络适配器列表（WMI Win32_NetworkAdapterConfiguration：
/// Description / IP / DHCPEnabled / DNSServerSearchOrder / 网关 / MAC）
Future<List<AdapterInfo>> getAdapterinfoList() =>
    RustLib.instance.api.crateApiSysinfoGetAdapterinfoList();

/// DHCP / DNS 状态：首元素为 DHCP 是否开启（"true"/"false"），其后为 DNS 服务器列表。
/// 取第一个有 IP 的适配器，没有则取第一个适配器。
Future<List<String>> getDhcpAndDnsStatus() =>
    RustLib.instance.api.crateApiSysinfoGetDhcpAndDnsStatus();

/// 是否开启了手动代理（HKCU\...\Internet Settings\ProxyEnable != 0）
Future<bool> hasManualProxy() =>
    RustLib.instance.api.crateApiSysinfoHasManualProxy();

/// hosts 是否被配置过（存在非默认行）
Future<bool> hostConfiged() =>
    RustLib.instance.api.crateApiSysinfoHostConfiged();

/// 外网连通性探测：TCP 连接 1.1.1.1:80，1 秒超时
Future<bool> netAvailable() =>
    RustLib.instance.api.crateApiSysinfoNetAvailable();

/// 用记事本打开 hosts 文件，返回 hosts 路径
Future<String> notepadOpenHost() =>
    RustLib.instance.api.crateApiSysinfoNotepadOpenHost();

/// 打开系统“代理服务器”设置页（ms-settings:network-proxy）
Future<void> openSettingNetworkProxyPage() =>
    RustLib.instance.api.crateApiSysinfoOpenSettingNetworkProxyPage();

/// 把指定适配器的 DNS 恢复为 DHCP 自动获取（netsh，需管理员权限）
Future<void> setAdapterDhcp({required String adapterName}) =>
    RustLib.instance.api
        .crateApiSysinfoSetAdapterDhcp(adapterName: adapterName);

/// 设置指定适配器的静态 DNS（netsh interface ip set/add dns，需管理员权限）。
/// dns_servers[0] 为主 DNS，其余按 index 依次追加为备用 DNS。
Future<void> setAdapterDns(
        {required String adapterName, required List<String> dnsServers}) =>
    RustLib.instance.api.crateApiSysinfoSetAdapterDns(
        adapterName: adapterName, dnsServers: dnsServers);

/// 网络修复：刷新 DNS 缓存 + 重置 Winsock 目录。
/// 注意：netsh winsock reset 需要管理员权限，且重置后需重启系统才能完全生效。
Future<void> setNetworkFix() =>
    RustLib.instance.api.crateApiSysinfoSetNetworkFix();

/// 枚举已安装应用（HKLM Uninstall + WOW6432Node + HKCU Uninstall），
/// 过滤 DisplayName 为空的项。
Future<List<InstalledAppInfo>> checkApp2() =>
    RustLib.instance.api.crateApiSysinfoCheckApp2();

/// 取应用图标像素：SHGetFileInfoW 取 shell 大图标 → GetIconInfo 拆颜色/蒙版位图
/// → GetDIBits 读 32bpp 顶层行序 → BGRA 换 RGBA。
/// 颜色面没有 alpha 的老式图标改用 1bpp AND 蒙版定透明度（蒙版位 1 为透明）。
/// 图标取不到时报错，由界面降级成占位图，不影响列表其它信息。
Future<AppIconPixels> extractAppIcon({required String displayIcon}) =>
    RustLib.instance.api
        .crateApiSysinfoExtractAppIcon(displayIcon: displayIcon);

/// 启动指定应用的卸载程序：按 uninstall_key 定位注册表项并执行其 UninstallString。
/// 卸载串可能自带引号与参数，交给 cmd /C 解析执行。
Future<void> uninstallApp({required String uninstallKey}) =>
    RustLib.instance.api
        .crateApiSysinfoUninstallApp(uninstallKey: uninstallKey);

/// 监控式卸载。
/// TODO：参考实现在启动卸载程序后会轮询等待卸载进程退出并回报进度；
/// 当前先复用直接启动逻辑，监控循环留待后续补充。
Future<void> uninstallAppMoint({required String uninstallKey}) =>
    RustLib.instance.api
        .crateApiSysinfoUninstallAppMoint(uninstallKey: uninstallKey);

/// 创建并以自动方式启动服务（sc.exe create + start，需管理员权限）。
/// sc 的经典语法要求 "binPath=" 与值分开传参，这里保持一致。
Future<void> installStartService(
        {required String serviceName, required String binPath}) =>
    RustLib.instance.api.crateApiSysinfoInstallStartService(
        serviceName: serviceName, binPath: binPath);

/// 版本号分段比较。返回单元素向量："1"=a 更新，"0"=相同，"-1"=a 更旧。
/// 以 . - _ 作为分段符；数字段按数值比较，否则按字符串比较。
Future<List<String>> judgeVersion(
        {required String versionA, required String versionB}) =>
    RustLib.instance.api
        .crateApiSysinfoJudgeVersion(versionA: versionA, versionB: versionB);

/// 停止并重新启动服务（sc stop → 等待 1.5s → sc start，需管理员权限）。
/// 若服务进程僵死导致 stop 失败，可由上层先 taskkill /F 再调用本接口。
Future<void> killRestartService({required String serviceName}) =>
    RustLib.instance.api
        .crateApiSysinfoKillRestartService(serviceName: serviceName);

/// 查询服务状态（sc.exe query，解析 STATE 行），返回 RUNNING/STOPPED/UNKNOWN 等。
Future<String> serviceStatus({required String serviceName}) =>
    RustLib.instance.api.crateApiSysinfoServiceStatus(serviceName: serviceName);

/// 启动服务（sc.exe start），返回命令输出
Future<String> startService({required String serviceName}) =>
    RustLib.instance.api.crateApiSysinfoStartService(serviceName: serviceName);

/// 机型类型：WMI Win32_ComputerSystem。
/// PCSystemType 映射（按原口径推断）：1=PC（台式）、2=System（移动/笔记本）、
/// 3=Workstation，其余为 Unspecified。
/// 返回 [类型, 厂商, 型号]。
Future<List<String>> getComputerType() =>
    RustLib.instance.api.crateApiSysinfoGetComputerType();

/// Windows 详细版本号（读 HKLM\...\CurrentVersion 注册表，保留原拼写 detial）。
/// 返回 [ProductName, DisplayVersion, CurrentBuild, UBR, EditionID]。
Future<List<String>> getWinDetialVer() =>
    RustLib.instance.api.crateApiSysinfoGetWinDetialVer();

/// 路径是否存在（保留原拼写 exits）
Future<bool> isPathExits({required String path}) =>
    RustLib.instance.api.crateApiSysinfoIsPathExits(path: path);

/// 把系统信息（版本 + 机型）写入 %ProgramData%\cm_rebuild\os_info.json
Future<void> setOsInfo() => RustLib.instance.api.crateApiSysinfoSetOsInfo();

/// 启动 exe，返回子进程 PID 字符串
Future<String> startExe({required String exePath}) =>
    RustLib.instance.api.crateApiSysinfoStartExe(exePath: exePath);

/// CPU 信息：先刷新一次建立采样基线，sleep 300ms 后再刷新取使用率。
/// 返回 [CPU 名称, 逻辑核数, 使用率%（保留 1 位小数）]。
Future<List<String>> readCupInfo() =>
    RustLib.instance.api.crateApiSysinfoReadCupInfo();

/// 鼠标坐标（windows crate GetCursorPos），返回 [x, y] 字符串
Future<List<String>> getCursorPos() =>
    RustLib.instance.api.crateApiSysinfoGetCursorPos();

/// 磁盘列表（sysinfo::Disks；盘符取挂载点尾段，如 "C:"）
Future<List<DiskInfo>> getDiskInfoList() =>
    RustLib.instance.api.crateApiSysinfoGetDiskInfoList();

/// 系统盘（根盘）信息：按 %SystemDrive% 环境变量匹配盘符，找不到返回 None
Future<DiskInfo?> getRootDiskInfo() =>
    RustLib.instance.api.crateApiSysinfoGetRootDiskInfo();

/// 收集日志：把 exe 目录下 logs\ 最近 7 天的文件复制到
/// %TEMP%\cm_collect_<时间戳>\ 并打包为 %TEMP%\cm_collect_<时间戳>.zip，
/// 返回 zip 路径。logs 目录不存在时仍会生成带清单的空包。
Future<List<String>> collectLog() =>
    RustLib.instance.api.crateApiSysinfoCollectLog();

/// 内存优化：对每个可打开的进程调用 SetProcessWorkingSetSize(h, -1, -1)
/// 修剪工作集（即“整理内存”），返回 "trimmed=<数量>"。
/// 注意：对无权限访问的系统进程会被自动跳过。
Future<String> processesMemoryOptimization() =>
    RustLib.instance.api.crateApiSysinfoProcessesMemoryOptimization();

/// 内存使用情况（字节）：sysinfo 刷新后取 used/total
Future<MemoryInfo> readMemory2() =>
    RustLib.instance.api.crateApiSysinfoReadMemory2();

/// 网络信息：UDP “假连接”（不实际发包）取本机出口 IPv4，
/// 再用 TCP 连接 1.1.1.1:80（1 秒超时）判断外网连通性。
Future<NetInfo> getNetInfo() =>
    RustLib.instance.api.crateApiSysinfoGetNetInfo();

/// 网络质量实测：RTT 取 TCP 握手耗时（探测点与 `get_net_info` 一致，不引入新域名），
/// 收发量取网卡计数器在窗口两端的差值。参考实现 net_speed_test 页是拉一个测速文件
/// 算带宽上限，测速源属于运营方后端，净室分支没有等价物，因此这里只报本机确实
/// 测得出的两个量：链路往返时延、窗口内实际吞吐。
Future<NetQuality> measureNetQuality({required int samples}) =>
    RustLib.instance.api.crateApiSysinfoMeasureNetQuality(samples: samples);

/// 已安装补丁 ID 列表（WMI Win32_QuickFixEngineering 的 HotFixID）
Future<List<String>> getInstalledPatchIds() =>
    RustLib.instance.api.crateApiSysinfoGetInstalledPatchIds();

/// 需要重启才生效的挂起点，返回命中的来源标识（可能多个，也可能为空）。
///
/// 参考实现文案表自带「存在需要重启云电脑才生效的补丁」（zh_strings.txt:260），
/// 说明补丁页会报这个状态。这里只读 Windows 自己写下的三个挂起点，不猜：
/// - `cbs`：Component Based Servicing\RebootPending —— 组件服务在等重启，这才是「补丁」；
/// - `wu`：WindowsUpdate\Auto Update\RebootRequired —— Windows Update 在等重启；
/// - `rename`：Session Manager 的 PendingFileRenameOperations —— 安装器留下的待替换/
///   待删除文件，重启后才处理，但它不代表补丁，所以界面上的措辞要分开。
/// 三个键普通用户都可读，读不到（不存在）就是没有挂起。
Future<List<String>> rebootPendingReasons() =>
    RustLib.instance.api.crateApiSysinfoRebootPendingReasons();

/// 用 wusa.exe 静默安装指定 KB 补丁（/quiet /norestart，需管理员权限）。
/// kb_id 可传 "KB5031354" 或 "5031354"，内部抽取数字段。
Future<String> wusaInstallPatch({required String kbId}) =>
    RustLib.instance.api.crateApiSysinfoWusaInstallPatch(kbId: kbId);

/// 用 dism.exe 安装补丁包（.cab 等），需管理员权限
Future<String> dismInstallPatch({required String packagePath}) =>
    RustLib.instance.api
        .crateApiSysinfoDismInstallPatch(packagePath: packagePath);

/// 用 dism.exe 卸载补丁包（按包名），需管理员权限
Future<String> dismUninstallPatch({required String packageName}) =>
    RustLib.instance.api
        .crateApiSysinfoDismUninstallPatch(packageName: packageName);

/// 用 msiexec.exe 静默安装 MSI 补丁包（/quiet /norestart），需管理员权限
Future<String> msiPatchInstall({required String packagePath}) =>
    RustLib.instance.api
        .crateApiSysinfoMsiPatchInstall(packagePath: packagePath);

/// 按扩展名自动分发补丁安装：.msu → wusa，.msi → msiexec，.cab → dism
Future<String> commonPatchInstall({required String packagePath}) =>
    RustLib.instance.api
        .crateApiSysinfoCommonPatchInstall(packagePath: packagePath);

/// 用 wusa.exe 静默卸载指定 KB 补丁（wusa /uninstall /kb:ID /quiet /norestart），
/// 需管理员权限
Future<String> wusaUninstallPatch({required String kbId}) =>
    RustLib.instance.api.crateApiSysinfoWusaUninstallPatch(kbId: kbId);

/// 进程 exe 的文件描述（PE VERSIONINFO 的 FileDescription）。
/// 参数为 exe 完整路径（pid → path 由上层用进程列表转换）。
Future<List<String>> getProcessFileDescription({required String exePath}) =>
    RustLib.instance.api
        .crateApiSysinfoGetProcessFileDescription(exePath: exePath);

/// 进程图标（codec 面：`crateApiSysinfoProcessProcessInfoGetProcessIco`，返回字符串列表）。
/// 参考实现把 HICON 编成 PNG 再交给前端，但这条 codec 的返回类型是 `List<String>`，
/// 规格清单看不出字符串里装的是路径还是编码后的位图，故保持返回 exe 路径；
/// 前端图标实际由 [extract_app_icon] 直接取 RGBA 像素渲染，不经这条路。
Future<List<String>> getProcessIco({required String exePath}) =>
    RustLib.instance.api.crateApiSysinfoGetProcessIco(exePath: exePath);

/// 进程 exe 的发布者（PE VERSIONINFO 的 CompanyName）。
Future<List<String>> getProcessPublisher({required String exePath}) =>
    RustLib.instance.api.crateApiSysinfoGetProcessPublisher(exePath: exePath);

/// 记录并返回端口占用（netstat -ano，中文系统输出为本地编码，逐行返回）。
/// 同时写入 rust 日志（log::info!）。
Future<List<String>> logProcessPortUsage() =>
    RustLib.instance.api.crateApiSysinfoLogProcessPortUsage();

/// 进程列表（按内存占用降序，取前 50 条）。
/// 首次刷新建立采样基线，sleep 300ms 后再刷新以获得 CPU 占用。
Future<List<ProcessEntry>> readProcessInfo() =>
    RustLib.instance.api.crateApiSysinfoReadProcessInfo();

/// 结束指定进程（sysinfo Process::kill）
Future<void> terminateProcess({required int pid}) =>
    RustLib.instance.api.crateApiSysinfoTerminateProcess(pid: pid);

/// 开机启动项列表：HKCU\...\Run + HKLM\...\Run + HKLM Wow6432Node\...\Run
Future<List<StartupItemInfo>> readStartupList() =>
    RustLib.instance.api.crateApiSysinfoReadStartupList();

/// 修改启动项启用状态：写 StartupApproved（禁用 = 03 00 00 00...）。
/// location 取 read_startup_list 返回的标记："HKCU" / "HKLM" / "HKLM_WOW"。
/// 注意：写 HKLM 侧的 StartupApproved 需要管理员权限。
Future<void> changeStartupStatus(
        {required String itemName,
        required bool enable,
        required String location}) =>
    RustLib.instance.api.crateApiSysinfoChangeStartupStatus(
        itemName: itemName, enable: enable, location: location);

/// 开机时长（毫秒）：WMI Win32_OperatingSystem.LastBootUpTime 与当前时间之差。
/// 返回单元素向量（毫秒字符串）。WMI 时间形如 "20240105103000.500000+480"，
/// 取前 14 位按本地时间与本地当前时间相减，时区偏移自然抵消。
Future<List<String>> getSystemBootUpDuration() =>
    RustLib.instance.api.crateApiSysinfoGetSystemBootUpDuration();

/// 启动项名称列表（read_startup_list 的 name 列）
Future<List<String>> getName() => RustLib.instance.api.crateApiSysinfoGetName();

/// 存储感知开关状态：读 HKCU\...\StoragePolicy 的 "01" DWORD（0=关 1=开），
/// 键不存在视为关闭。返回单元素向量。
Future<List<String>> getStrogeSense() =>
    RustLib.instance.api.crateApiSysinfoGetStrogeSense();

/// 设置存储感知开关：写 HKCU\...\StoragePolicy 的 "01" DWORD（1/0）
Future<void> setStrogeSense({required bool enabled}) =>
    RustLib.instance.api.crateApiSysinfoSetStrogeSense(enabled: enabled);

/// 打开系统“存储感知”设置页（ms-settings:storagesense）
Future<void> showStrogeSense() =>
    RustLib.instance.api.crateApiSysinfoShowStrogeSense();

/// 执行镜像升级包：校验存在后按扩展名分发（exe 直接启动、msu 走 wusa、
/// bat/cmd 交给 cmd /C），不等待执行完成
Future<void> execImagePackage({required String packagePath}) =>
    RustLib.instance.api
        .crateApiSysinfoExecImagePackage(packagePath: packagePath);

/// 镜像升级版本：读 C:\ProgramData\\ImageUpgrade\version.txt，
/// 文件不存在返回空向量
Future<List<String>> getImageVersion() =>
    RustLib.instance.api.crateApiSysinfoGetImageVersion();

/// 是否 x86（32 位）CPU 架构编译目标
Future<bool> isX86Cpu() => RustLib.instance.api.crateApiSysinfoIsX86Cpu();

/// 应用列表：枚举开始菜单（所有用户 + 当前用户）的 .lnk 项，
/// 去重排序后最多返回 500 条
Future<List<String>> getAppInfo() =>
    RustLib.instance.api.crateApiSysinfoGetAppInfo();

/// Windows 版本信息：读 HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion 的
/// ProductName / DisplayVersion / CurrentBuild / UBR，拼接为单个字符串返回。
Future<List<String>> getVersionInfo() =>
    RustLib.instance.api.crateApiSysinfoGetVersionInfo();

/// 打开应用：路径存在则直接 spawn，否则交给 cmd start 按名称/协议解析
Future<void> openApp({required String target}) =>
    RustLib.instance.api.crateApiSysinfoOpenApp(target: target);

/// 网络适配器信息（对应 WMI Win32_NetworkAdapterConfiguration）
class AdapterInfo {
  final String description;
  final String macAddress;
  final List<String> ipAddresses;
  final List<String> gateways;
  final bool dhcpEnabled;
  final List<String> dnsServers;

  const AdapterInfo({
    required this.description,
    required this.macAddress,
    required this.ipAddresses,
    required this.gateways,
    required this.dhcpEnabled,
    required this.dnsServers,
  });

  @override
  int get hashCode =>
      description.hashCode ^
      macAddress.hashCode ^
      ipAddresses.hashCode ^
      gateways.hashCode ^
      dhcpEnabled.hashCode ^
      dnsServers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdapterInfo &&
          runtimeType == other.runtimeType &&
          description == other.description &&
          macAddress == other.macAddress &&
          ipAddresses == other.ipAddresses &&
          gateways == other.gateways &&
          dhcpEnabled == other.dhcpEnabled &&
          dnsServers == other.dnsServers;
}

/// 应用图标像素（行主序 RGBA），由界面直接解码成图片，不需要经过 PNG 编码。
/// width/height 取自图标自身的颜色位图，因此不同机器上的 32/48px 图标都能如实呈现。
class AppIconPixels {
  final int width;
  final int height;
  final Uint8List rgba;

  const AppIconPixels({
    required this.width,
    required this.height,
    required this.rgba,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ rgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppIconPixels &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          rgba == other.rgba;
}

/// 磁盘信息
class DiskInfo {
  /// 盘符（取挂载点尾段，如 "C:"）
  final String name;

  /// 挂载点（如 "C:\\"）
  final String mountPoint;

  /// 总容量（字节）
  final BigInt totalBytes;

  /// 剩余容量（字节）
  final BigInt freeBytes;

  /// 文件系统（NTFS/FAT32...）
  final String fileSystem;

  /// 是否可移动介质
  final bool removable;

  const DiskInfo({
    required this.name,
    required this.mountPoint,
    required this.totalBytes,
    required this.freeBytes,
    required this.fileSystem,
    required this.removable,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      mountPoint.hashCode ^
      totalBytes.hashCode ^
      freeBytes.hashCode ^
      fileSystem.hashCode ^
      removable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiskInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          mountPoint == other.mountPoint &&
          totalBytes == other.totalBytes &&
          freeBytes == other.freeBytes &&
          fileSystem == other.fileSystem &&
          removable == other.removable;
}

/// 已安装应用（卸载注册表项）
class InstalledAppInfo {
  final String name;
  final String version;
  final String publisher;

  /// 完整卸载注册表键，形如 "HKLM\SOFTWARE\...\Uninstall\{GUID}"
  final String uninstallKey;
  final String uninstallString;

  /// DisplayIcon 原值，形如 `"C:\Path\a.exe",0` 或 `a.exe,1`；可能为空
  final String displayIcon;

  const InstalledAppInfo({
    required this.name,
    required this.version,
    required this.publisher,
    required this.uninstallKey,
    required this.uninstallString,
    required this.displayIcon,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      version.hashCode ^
      publisher.hashCode ^
      uninstallKey.hashCode ^
      uninstallString.hashCode ^
      displayIcon.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InstalledAppInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          version == other.version &&
          publisher == other.publisher &&
          uninstallKey == other.uninstallKey &&
          uninstallString == other.uninstallString &&
          displayIcon == other.displayIcon;
}

/// 内存信息（单位：字节）
class MemoryInfo {
  /// 已用内存（字节）
  final BigInt used;

  /// 总内存（字节）
  final BigInt total;

  const MemoryInfo({
    required this.used,
    required this.total,
  });

  @override
  int get hashCode => used.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemoryInfo &&
          runtimeType == other.runtimeType &&
          used == other.used &&
          total == other.total;
}

/// 网络状态
class NetInfo {
  /// 本机出口 IPv4（探测失败时为空串）
  final String localIp;

  /// 是否可连通外网（TCP 连接 1.1.1.1:80，1 秒超时）
  final bool connected;

  const NetInfo({
    required this.localIp,
    required this.connected,
  });

  @override
  int get hashCode => localIp.hashCode ^ connected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetInfo &&
          runtimeType == other.runtimeType &&
          localIp == other.localIp &&
          connected == other.connected;
}

/// 一次网络实测结果。
class NetQuality {
  /// 每次 TCP 握手的往返耗时（毫秒）；连不上的探测直接丢弃，所以可能为空
  final Uint64List rttMs;

  /// 采样窗口内本机网卡实收/实发字节
  final BigInt receivedBytes;
  final BigInt transmittedBytes;

  /// 采样窗口长度（毫秒），速率由调用方按 bytes*8/window 换算
  final BigInt windowMs;

  const NetQuality({
    required this.rttMs,
    required this.receivedBytes,
    required this.transmittedBytes,
    required this.windowMs,
  });

  @override
  int get hashCode =>
      rttMs.hashCode ^
      receivedBytes.hashCode ^
      transmittedBytes.hashCode ^
      windowMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetQuality &&
          runtimeType == other.runtimeType &&
          rttMs == other.rttMs &&
          receivedBytes == other.receivedBytes &&
          transmittedBytes == other.transmittedBytes &&
          windowMs == other.windowMs;
}

/// 进程条目（进程列表页）
class ProcessEntry {
  final int pid;
  final String name;

  /// 进程 exe 全路径；无权限查询（系统进程、其它用户）时为空
  final String exe;

  /// CPU 占用百分比
  final double cpu;

  /// 物理内存占用（MB）
  final double memMb;

  const ProcessEntry({
    required this.pid,
    required this.name,
    required this.exe,
    required this.cpu,
    required this.memMb,
  });

  @override
  int get hashCode =>
      pid.hashCode ^
      name.hashCode ^
      exe.hashCode ^
      cpu.hashCode ^
      memMb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessEntry &&
          runtimeType == other.runtimeType &&
          pid == other.pid &&
          name == other.name &&
          exe == other.exe &&
          cpu == other.cpu &&
          memMb == other.memMb;
}

/// 开机启动项
class StartupItemInfo {
  /// 启动项名称（Run 键值名）
  final String name;

  /// 启动命令
  final String command;

  /// 来源标记："HKCU" / "HKLM" / "HKLM_WOW"
  final String location;

  /// 是否启用（依据 StartupApproved 首字节）
  final bool enabled;

  const StartupItemInfo({
    required this.name,
    required this.command,
    required this.location,
    required this.enabled,
  });

  @override
  int get hashCode =>
      name.hashCode ^ command.hashCode ^ location.hashCode ^ enabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StartupItemInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          command == other.command &&
          location == other.location &&
          enabled == other.enabled;
}
