// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `app_dir`

/// 向 UI 通知队列追加一条消息（非 frb 接口，供本 crate 其它模块调用）。
/// TODO(集成期)：sysinfo / disk_scan 等模块尚未接入推送，接入后无需再改本函数。
Future<void> pushNotify({required String msg}) =>
    RustLib.instance.api.crateApiUtilsPushNotify(msg: msg);

/// 读取机器唯一标识：
/// 1) 首选注册表 HKLM\SOFTWARE\Microsoft\Cryptography\MachineGuid（与参考实现一致）；
/// 2) 注册表失败则回退 exe 目录 `machine_id` 缓存文件；
/// 3) 缓存不存在则生成 uuid v4 写入缓存并返回，保证后续运行稳定。
Future<String> getMachineId() =>
    RustLib.instance.api.crateApiUtilsGetMachineId();

/// 获取应用当前目录（当前 exe 所在目录），字符串形式返回。
Future<String> getAppCurrentDir() =>
    RustLib.instance.api.crateApiUtilsGetAppCurrentDir();

/// 创建单实例互斥体：已存在同名实例时直接退出进程（参考实现防多开行为）。
///
/// windows 0.58 的 `CreateMutexW` 仅在句柄无效（真正创建失败）时返回 `Err`；
/// “互斥体已存在”时仍返回 `Ok(有效句柄)`，因此成功后需立即读取 GetLastError 判定。
Future<void> createMutex() => RustLib.instance.api.crateApiUtilsCreateMutex();

/// 设置进程环境变量。
Future<void> setEnv({required String key, required String value}) =>
    RustLib.instance.api.crateApiUtilsSetEnv(key: key, value: value);

/// 设置开发模式开关（写入环境变量 IS_DEV，"true"/"false"）。
Future<void> setIsDev({required bool isDev}) =>
    RustLib.instance.api.crateApiUtilsSetIsDev(isDev: isDev);

/// 取走（drain）全部待通知消息并以换行拼接返回；无消息时返回空字符串。
Future<String> getRustNotifyMsg() =>
    RustLib.instance.api.crateApiUtilsGetRustNotifyMsg();

/// 启动主进程数据采集。
///
/// 说明：真实的系统数据采集（CPU/内存/进程等）由常驻 agent 进程（cm_agent bin）
/// 负责；GUI 侧此调用仅保留一个低频心跳线程占位，不阻塞 UI 线程。
Future<void> mainCollect() => RustLib.instance.api.crateApiUtilsMainCollect();

/// 后端初始化：确保 exe 目录下 logs\ 存在，并输出初始化标记日志。
Future<void> rustBackendInit() =>
    RustLib.instance.api.crateApiUtilsRustBackendInit();

/// 后端清理：删除 exe 目录 temp\ 下修改时间超过 24 小时的文件。
Future<void> rustBackendClean() =>
    RustLib.instance.api.crateApiUtilsRustBackendClean();

/// 重启应用：拉起当前 exe 后立即退出当前进程（正常路径不会返回）。
Future<void> restartApplication2() =>
    RustLib.instance.api.crateApiUtilsRestartApplication2();

/// 创建指定大小的空白临时文件（按 mtime/大小占位用）。
///
/// 注意：函数名沿用原工程拼写（tmep / whit），刻意保留以保证 codec 对齐。
Future<void> createTmepEmptyFileWhitSize(
        {required String path, required BigInt size}) =>
    RustLib.instance.api
        .crateApiUtilsCreateTmepEmptyFileWhitSize(path: path, size: size);
